client/urls.py
from django.urls import path

from . import views

app_name = 'client'
urlpatterns = [
    path('', views.login_page, name='login_page'),
    path('client', views.client_page, name='client_page'),
    path('<int:days_to_show>/<str:data_type>', views.client_page, name='client_page'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', include('client.urls')),
    path('admin/', admin.site.urls),
    path('client/', include('client.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('', include('pwa.urls')),
]

main/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index')
]

client/models.py
from django.contrib.auth.models import User

from django.db import models


class Airconddata(models.Model):
    id = models.BigAutoField(primary_key=True)
    time = models.DateTimeField()
    t1 = models.SmallIntegerField(blank=True, null=True)
    t2 = models.SmallIntegerField(blank=True, null=True)
    t3 = models.SmallIntegerField(blank=True, null=True)
    t4 = models.SmallIntegerField(blank=True, null=True)
    t5 = models.SmallIntegerField(blank=True, null=True)
    pressure = models.SmallIntegerField(blank=True, null=True)
    current = models.SmallIntegerField(blank=True, null=True)

    client = models.ForeignKey(User, on_delete=models.CASCADE)
    telegram_chat_id = models.BigIntegerField(blank=True, null=True)

    cond_id = models.SmallIntegerField(blank=True, null=True)
    airconds_count = models.SmallIntegerField(blank=True, null=True)


class Person(models.Model):
    """One-to-one model to add telegram id for a user"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telegram_chat_id = models.BigIntegerField(blank=True, null=True)

client/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import services


def client_page(request, days_to_show='', data_type='graph'):
    user = request.user
    if services.check_anonymous(user):
        grafana_data = services.get_data(user, days=days_to_show, data_type=data_type)
        current_data = services.get_current_data(user)
        errors = services.get_errors(user)
        users = services.get_users(user)
        return render(request, 'client/client.html', {'user': request.user,
                                                      'grafana_data': grafana_data,
                                                      'current_data': current_data,
                                                      'errors': errors,
                                                      'users': users})
    else:
        return redirect('/')


def login_page(request):
    return render(request, 'client/login.html')


def login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    user = services.signin(request, username, password)
    if isinstance(user, str):
        return HttpResponse(user)

    return redirect('/client')


def logout(request):
    services.sign_out(request)
    return redirect('/')

main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/main_page.html')

templates/client/client.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="{% static 'client/css/client.css' %}">
        <title>Личный кабинет</title>
        <!-- <link rel="shortcut icon" type="image/png" href="img/favicon.ico" /> -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div id="header">
            <div id="logo">
                <img id="logo_img" src="{% static '/main/img/logo_img.png' %}" >
            </div>
            <div id="user">
                <div id="user_info">
                    <div>{{ user.username }}</div>
                </div>
                <div class="button" onclick="delCookies()"> ВЫЙТИ </div>
                <a id="hidden_button" style="display: none;" href="{% url 'client:logout' %}"></a>

            </div>    
        </div>
        <div id='body'>
            <div id="interface">
                <div id="errors">
                    {% for cond_error in errors %}
                        {% for key, value in cond_error.items %}
                            <p>{{key}}: {{value}}</p>
                        {% endfor %}
                    {% endfor %}
                </div>
                <div id="device_info">
                    {% for key, value in current_data.items %}
                        <p>{{key}}:  {{value}}</p>
                    {% endfor %}
                </div>
                <div id="buttons">
                    <div class="button_block">
                        <div class="button_group">Графики</div>
                        <div class="button_box">
                            <a href="{% url 'client:client_page' days_to_show=7 data_type='graph'%}" class="button">7 дней</a>
                            <a href="{% url 'client:client_page' days_to_show=1 data_type='graph'%}" class="button">1 день</a>
                        </div>
                    </div>
                    <div class="button_block">
                        <div class="button_group">Таблицы</div>
                        <div class="button_box">
                            <a href="{% url 'client:client_page' days_to_show=1 data_type='table'%}" class="button">7 дней</a>
                            <a href="{% url 'client:client_page' days_to_show=1 data_type='table'%}" class="button">1 день</a>
                        </div>    
                    </div>
                </div>
            </div>
            <div id="chart">
                {% for data in grafana_data %}
                    <div class="grafana">
                        <iframe src="{{ data }}" width="100%" height="100%" frameborder="0"></iframe>
                    </div>   
                {% endfor %}
            </div>
        </div>
        
        <script src="{% static 'client/js/client.js' %}"></script>
    </body>
</html>

templates/client/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load pwa %}
        {% progressive_web_app_meta %}
        <meta charset="UTF-8">
        <title>Авторизация</title>
        <link rel="stylesheet" href="{% static 'client/css/login.css' %}">
        <link rel="shortcut icon" type="image/png" href="img/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div id="wrapper">
            <div id="logo">
                <img src="{% static '/main/img/logo.png' %}" >
            </div>
            <!-- <div id="main_text">Авторизация</div> -->
            <form id="signin_form" method="post" action="{% url 'client:login' %}" onchange="setCookies()">
                {% csrf_token %}
                <input type="text" id="user" placeholder="ЛОГИН" name="username"/>
                <input type="password" id="pass" placeholder="ПАРОЛЬ" name="password"/>
                <button type="submit" class="button" id="post_button">ВОЙТИ</button>
            </form>
        </div>
        
        <script src="{% static 'client/js/login.js' %}"></script>
    </body>
</html>

templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Авторизация</title>
    <link rel="stylesheet" href="{% static 'login/css/login.css' %}">
    <link rel="stylesheet" href="../../static/login/css/login.css">
</head>
<body>
    <div id="wrapper">
        <h1 id="login_header">Авторизация</h1>
        <form id="signin" method="" action="">
            <input type="text" id="user" placeholder="логин" />
            <input type="password" id="pass" placeholder="пароль" />
            <button type="submit">&#xf0da;</button>
            <a href="#">Создать аккаунт</a>
        </form>
    </div>
</body>
</html>